# Generated by Django 3.2.4 on 2021-07-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0004_allifmaalvehiclestable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_files', models.FileField(upload_to='')),
            ],
        ),
    ]
