# Generated by Django 3.2.4 on 2021-07-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0005_uploadfiletable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image_files', models.FileField(upload_to='books/pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFileTable',
        ),
    ]
