# Generated by Django 3.2.4 on 2021-07-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0006_auto_20210722_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiletable1',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
