# Generated by Django 3.2.4 on 2021-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0012_alter_allifmaalstocktable1_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allifmaalstocktable1',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allifmaalstocktable1',
            name='quantity_in_store',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
