# Generated by Django 3.2.4 on 2021-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0016_auto_20210729_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allifmaalhrmtable',
            name='joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
