# Generated by Django 3.2.4 on 2021-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0017_alter_allifmaalhrmtable_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allifmaalhrmtable',
            name='joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
