# Generated by Django 3.2.4 on 2021-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0018_alter_allifmaalhrmtable_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allifmaalhrmtable',
            name='joined',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
