# Generated by Django 3.2.4 on 2021-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0021_alter_allifmaalhrmtable2_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allifmaalhrmtable2',
            name='joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
