# Generated by Django 3.2.4 on 2021-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0022_alter_allifmaalhrmtable2_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllifmaalHRMTable2Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='allifmaalstocktable1',
            name='quantity_in_store',
            field=models.IntegerField(null=True),
        ),
    ]
