# Generated by Django 3.2.4 on 2021-07-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0024_invoicetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetable',
            old_name='customer_name',
            new_name='item_name',
        ),
    ]
