# Generated by Django 3.2.4 on 2021-07-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0025_rename_customer_name_invoicetable_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetable',
            old_name='item_name',
            new_name='customer_name',
        ),
    ]
