# Generated by Django 3.2.4 on 2021-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0026_rename_item_name_invoicetable_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allifmaalstocktable1',
            name='line_total',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='allifmaalstocktable1',
            name='sum_total',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
