# Generated by Django 3.2.4 on 2021-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allifmaalerpsystem', '0027_auto_20210802_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesDailyMileageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, choices=[('Truck', 'Truck'), ('Car', 'Car'), ('Pickup', 'Pickup'), ('Bus', 'Bus'), ('Trailer', 'Trailer'), ('Van', 'Van'), ('Tow Truck', 'Tow Truck'), ('Motorcycle', 'Motorcycle')], max_length=255, null=True)),
                ('vehicle_operator', models.CharField(blank=True, choices=[('Arnold', 'Arnold'), ('Rotich', 'Rotich')], max_length=255, null=True)),
                ('mileage_date', models.DateTimeField(blank=True, null=True)),
                ('starting_odometer', models.IntegerField(blank=True, default='0', null=True)),
                ('ending_odometer', models.IntegerField(blank=True, default='0', null=True)),
                ('notes', models.CharField(blank=True, choices=[('Kilometers', 'Kilometers'), ('Miles', 'Miles')], max_length=255, null=True)),
            ],
        ),
    ]
